d = int(input('Digite um número para ver sua tabuada: '))
print('-'*12)
print('{} x {:2} = {}'.format(d, 1, d*1))
print('{} x {:2} = {}'.format(d, 2, d*2))
print('{} x {:2} = {}'.format(d, 3, d*3))
print('{} x {:2} = {}'.format(d, 4, d*4))
print('{} x {:2} = {}'.format(d, 5, d*5))
print('{} x {:2} = {}'.format(d, 6, d*6))
print('{} x {:2} = {}'.format(d, 7, d*7))
print('{} x {:2} = {}'.format(d, 8, d*8))
print('{} x {:2} = {}'.format(d, 9, d*9))
print('{} x {:2} = {}'.format(d, 10, d*10))
print('-'*12)
